events:
  - name: planet_logs
    generators: 1
    vars:
      - name: version
        value: v1
    template: planet_logs.tmpl
  - name: raw_logs
    generators: 10
    raw: >
      <<list.left_names>> <<list.right_names>>
