sinks:
  http:
    localhost:
      url: http://localhost:8080
      method: post
      headers:
        - name: Content-Type
          value: application/json
        - name: X-Genie-Version
          value: v1
        - name: X-Event-Type
          value: logging
        - name: X-Request-Id
          resource: uuid.request_uuid
        - name: User-Agent
          resource: list.user_agent
events:
  planet_logs:
    generators: 1
    vars:
      - name: version
        value: v1
    template: planet_logs.tmpl
  raw_logs:
    generators: 1
    raw: >
      <% let left_name = list.left_names %>
      <% let right_name = list.right_names %>
      {"msg": "Hello <<left_name>> <<right_name>>!"}
