events:
  - name: myevent
    template: foo.gpl
resources:
  list:
    - name: mylist
  integer_range:
    - name: myrange
      min: 0
      max: 10
  random_string:
    - name: myrand
      length: 16
      charset: alpha|alphanum|etc
  uuid:
    - name: myuuid
  timestamp:
    - name: mytimestamp
  map:
    - name: mymap